additionalProperties:
  artifactId: test-artifact
files:
  ../kinde-elixir-sdk/lib/kinde_sdk/sdk/authorization_code.ex:
    destinationFilename: lib/kinde_sdk/sdk/authorization_code.ex
  ../kinde-elixir-sdk/lib/kinde_sdk/sdk/client_credentials.ex:
    destinationFilename: lib/kinde_sdk/sdk/client_credentials.ex
  ../kinde-elixir-sdk/lib/kinde_sdk/sdk/pkce.ex:
    destinationFilename: lib/kinde_sdk/sdk/pkce.ex
  ../kinde-elixir-sdk/lib/kinde_sdk/sdk/utils.ex:
    destinationFilename: lib/kinde_sdk/sdk/utils.ex
  ../kinde-elixir-sdk/lib/kinde_sdk/kinde_cache.ex:
    destinationFilename: lib/kinde_sdk/kinde_cache.ex
  ../kinde-elixir-sdk/lib/kinde_sdk/kinde_client_sdk.ex:
    destinationFilename: lib/kinde_sdk/kinde_client_sdk.ex
  ../kinde-elixir-sdk/test/authorization_code_test.exs:
    destinationFilename: test/authorization_code_test.exs
  ../kinde-elixir-sdk/test/client_credentials_test.exs:
    destinationFilename: test/client_credentials_test.exs
  ../kinde-elixir-sdk/test/pkce_test.exs:
    destinationFilename: test/pkce_test.exs
  ../kinde-elixir-sdk/test/kinde_client_sdk_test.exs:
    destinationFilename: test/kinde_client_sdk_test.exs
  ../kinde-elixir-sdk/test/utils_test.exs:
    destinationFilename: test/utils_test.exs
  ../kinde-elixir-sdk/test/client_test_helper.exs:
    destinationFilename: test/client_test_helper.exs
  ../kinde-elixir-sdk/test/test_helper.exs:
    destinationFilename: test/test_helper.exs
  